version: '3.1'
services:
  db:
    container_name: auth-nestjs_db
    image: postgres:14.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth-nestjs
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - '5445:5432'
    restart: always
    networks:
      - auth-nestjs
